import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import klaytnLogo from '../public/klaytn.jpg'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Klaytn NFT Minter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/klaytn.jpg" />
      </Head>

      <section className='sticky inset-x-0 top-0 z-10 h-20 min-w-full border-b border-red-600 bg-primary backdrop-filter backdrop-blur-lg bg-opacity-30'>
        <div className="px-10 flex items-center container mx-auto max-w-7xl justify-between h-full">
          <nav>
          {/* Logo */}
                <ul className='flex '>
                  <li>
                    <Image alt='Klaytn Logo' src={klaytnLogo} height={40} width={40} className='rounded-md'/>
                  </li>
                  <li>
                    <a className="text-2xl font-bold">
                    <span className="pr-2 text-transparent bg-clip-text bg-gradient-to-br from-red-800 to-orange-400">
                      laytn
                    </span>
                    </a>
                  </li>
                </ul>
          </nav>
          {/* Nav */}
          <section className='text-semibold text-transparent bg-clip-text bg-gradient-to-br from-red-800 to-orange-400 cursor-pointer'>
            <ul className="flex items-center space-x-8">
              <li className='hover:text-orange-400 hover:scale-y-150'>
                  <a>Gallery</a>
              </li>
              <li className='hover:text-orange-400 hover:scale-y-150'>
                  <a>About</a>
              </li>
              <li className='hover:text-orange-400 hover:scale-y-150'>
                  <a>FAQ</a>
              </li>
              <li className="hover:text-orange-400 hover:border-orange-400 cursor-pointer px-4 py-2 font-bold text-red-600 border border-red-500 rounded-md">
                <a>
                    <span className=''>Connect Wallet</span>
                </a>
              </li>
            </ul>
          </section>
          
        </div>
      </section>

      {/* Content */}
      <section>
        <div>


          <p></p>
          <br></br>
          <br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>
          <br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>
          <br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>
      
        </div>
      </section>

      {/* Footer */}
      <section className="flex h-24 w-auto items-center justify-center border-t border-red-600">
          <a
            className="flex items-center justify-center gap-2"
            href="https://www.teamdao.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <Image src="/ROUND.png" alt="TEAMDAO Logo" width={31} height={5} /><span className='text-lime-400'>T.E.A.M</span>
          </a>
        </section>
    </div>
  )
}

export default Home
